version: "3.6"

services:
    traefik:
        ports:
            # The HTTP port
            - "80:80"
            # The HTTPS port
            - "443:443"
            # The Web UI (enabled by --api.insecure=true) exposed through Traefik
            # - "8902:8080"
