#
# docker-compose -f docker-compose.yml -f docker-compose.npm.yml up -d
#

version: "3.6"

volumes:
    npm_data:
    npm_letsencrypt:
    npm_mysql:

services:
    npm:
        image: "jc21/nginx-proxy-manager:latest"
        container_name: npm
        restart: always
        ports:
            - "443:443"
            - "80:80"
            - "81:81"
        labels:
            hostname: "npm.lh"
            traefik.enable: true
            traefik.docker.network: traefik
            # There is only one port exposed for this container,
            # thus no need to define it explicitly
            traefik.http.services.npm.loadbalancer.server.port: "81"
        healthcheck:
            test: ["CMD", "/bin/check-health"]
            interval: 10s
            timeout: 3s
        environment:
            DB_MYSQL_HOST: "npm_db"
            DB_MYSQL_PORT: 3306
            DB_MYSQL_USER: "npm"
            DB_MYSQL_PASSWORD: "npm4lh"
            DB_MYSQL_NAME: "npm"
        volumes:
          - type: volume
            source: npm_data
            target: /data
          - type: volume
            source: npm_letsencrypt
            target: /etc/letsencrypt
        networks:
            - traefik

    npm_db:
        image: "jc21/mariadb-aria:latest"
        container_name: npm_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "npm"
            MYSQL_DATABASE: "npm"
            MYSQL_USER: "npm"
            MYSQL_PASSWORD: "npm4lh"
        volumes:
          - type: volume
            source: npm_mysql
            target: /var/lib/mysql
        networks:
            - traefik
